# code: language=ansible
---
- name: Force systemd to re-read configs.
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start TAK Server service.
  ansible.builtin.systemd:
    name: takserver
    enabled: true
    state: started
