---
- name: Enable EPEL repository on CentOS 7 and RHEL 7
  become: true
  yum:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
