- name: Install TAK Server
  tags: takserver
  include_tasks: "{{ item }}"
  loop:
    - update-ulimit.yml
    - update-yum.yml
    - install-epel.yml
    - update-yum.yml
    - install-psql.yml
    - install-takserver.yml
    - setup-takserver-db.yml
    - enable-start-takserver.yml
  when: ansible_distribution == "CentOS"
