# code: language=ansible
---
- name: Install psycopg2 Python module.
  ansible.builtin.dnf:
    name: python3-psycopg2
    state: present

- name: Setup TAK PostgreSQL Database.
  ansible.builtin.command: /opt/tak/db-utils/takserver-setup-db.sh
  args:
    creates: /var/lib/pgsql/10/data/PG_VERSION

- name: Set PostgreSQL password for TAK Server.
  become: true
  community.postgresql.postgresql_user:
    name: "{{ takserver_db_user }}"
    password: "{{ takserver_db_pass }}"
  become_user: postgres
