---
- name: Check if TAK PostgreSQL Database exists
  stat:
    path: /var/lib/pgsql/10/data/
  register: takserver_db_data

- name: Setup TAK PostgreSQL Database
  shell: /opt/tak/db-utils/takserver-setup-db.sh
  when: not takserver_db_data.stat.exists
