# code: language=ansible
---
- name: Increase PAM nofile limit to 32768.
  become: true
  community.general.pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: '32768'
  register: pam_limits_updated
  notify: Reload all system config settings.
