---
# handlers file for ansible-role-takserver

- name: Restart takserver.
  ansible.builtin.systemd:
    name: takserver
    state: restarted

- name: Reload all system config settings.
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    reload: true
